version: "3.8"

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy_retriever:
    build:
      context: .
      dockerfile: docker/retriever/Dockerfile
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  proxy_tester:
    build:
      context: .
      dockerfile: docker/tester/Dockerfile
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
